### ISSUE TITLE
R-angular Issues Because Life Is Bad

### ISSUE THREAD

**Issue by cochrancj** [cochrancj/Game_Of_Fitness#3]
ng-click & ng-repeat .... I can have one; but not both. 

I'm trying to shuffle cards randomly, populate the random cards, and have the ability to click on one single card and add a class to that card only. 

I can get either/or to work, currently. 

I also want to save the value of the card selected into a users' profile. THis is also not working. 

I've done every possible combo of ng-click and repeat and toggles and whatnot.

**Comment by DZGoldman** [comment]
I can (try to) help! I'm on three, or I could come up if you're situated

**Comment by cochrancj** [comment]
Dammit! I just saw your reply. Are you in today?

**Comment by DZGoldman** [comment]
Yep, on 3

**Comment by cochrancj** [comment]
Sweet! Be right down

**Comment by rapala61** [comment]
Daniel in person
