### ISSUE TITLE
CSS conflict issue 

### ISSUE THREAD

**Issue by cochrancj** [cochrancj/Game_Of_Fitness#5]
There is some sort of conflict between my css & the framework I'm using - Bulma - re: html and body height. They're not 100%; and I'm not sure why. The Internets are little help. 

Any ideas?

**Comment by CentroDL** [comment]
what order are your css files? make sure yours is UNDER bulma's so that yours overwrites the bulma styles when loaded. #lemmeknow

**Comment by cochrancj** [comment]
Yep. My sheet is above Bulma and inline styling of the HTML element isn't even working. But some pages are fine. This is aggravating.

**Comment by cochrancj** [comment]
Ha! Fixed It! I importanted the shit out of every type of sizing on my html + body elements.
