### ISSUE TITLE
CSS looking different on Heroku vs Locally

### ISSUE THREAD

**Issue by cochrancj** [cochrancj/Game_Of_Fitness#6]
It looks from the logs like no changes _actually_ took place on Heroku since this morning (23:30 actually, which has not happened yet)....

When I change something in the HTML, the change takes; the massive changes I've made in the CSS today do not. 

Emma has suggested that it is possibly a precompiling error like so: https://devcenter.heroku.com/articles/rails-asset-pipeline but we didn't want to break my site completely. 

Help with the weirdness.

**Comment by ajhofferber** [comment]
hey. want to take a look at this?

**Comment by cochrancj** [comment]
Yes!

**Comment by cochrancj** [comment]
Where are you at & where do you want me to be?

**Comment by ajhofferber** [comment]
want to come in the class?

**Comment by cochrancj** [comment]
K. Be right there
