### ISSUE TITLE
Continuing on with the inability to add card mana to the users' mana

### ISSUE THREAD

**Issue by cochrancj** [cochrancj/Game_Of_Fitness#7]
Current error is:

// Started PUT "/users/4" for ::1 at 2016-06-03 14:21:31 -0400
// Processing by UsersController#update as HTML
//   Parameters: {"mana"=>2, "cardid"=>1, "id"=>"4", "user"=>{"mana"=>2}}
//   User Load (0.4ms)  SELECT  "users".\* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 4]]
// Completed 404 Not Found in 2ms (ActiveRecord: 0.4ms)
//
// ActiveRecord::RecordNotFound (Couldn't find User with 'id'=4):
//   app/controllers/users_controller.rb:23:in `update'

And I'm absolutely out of ideas on what is wrong or how to fix it. It's probably too late to firebomb this project, isn't it?

**Comment by cochrancj** [comment]
Also: 
bin/rake assets:precompile 

git push heroku master 

heroku open 

is also no longer working to ensure css changes actually make it live onto Heroku. Do I need to blow this Heroku up and start over again again?

**Comment by ajhofferber** [comment]
hey. can you explain to me what you've tried since we were working on it earlier?

**Comment by ajhofferber** [comment]
did you add and commit the changes before pushing to heroku?

**Comment by cochrancj** [comment]
I spent a long time screwing up migrations trying to add a default value to the users' mana while trying to not rage quit;

I have no clue where to even begin finding an answer for the id mismatch I'm so frustrated with it;

And I added 5 or 6 things to the html element trying to fix the 100% issue on all pages - I tenuously have it working on local for all pages. 

I also took a walk and ate.

I added, committed and pushed the changes to Git before pushing to Heroku, then went back when that wasn't working, ran the precompile and re-pushed to see if that would take; and it did not.

**Comment by ajhofferber** [comment]
hmmmm. okay. maybe sure you always add and commit _after_ you run that precompile locally.

ill take a look at a few things and then come find you. is your code on github up to date?

**Comment by cochrancj** [comment]
It is. Gimme 2 secs - I just ran precompile again; let me add and commit again.

**Comment by cochrancj** [comment]
That worked (the precompile before add and commit). Whew. Computer fire averted temporarily.

**Comment by ajhofferber** [comment]
hooray!

i will look at what you've got goin on. we have to start doing those progress check ins, but I will def take a look and see what I can see!
